In [1]:
import pandas as pd
import numpy as np


In [4]:
# randint(start from, end on, size = ())
data = np.random.randint(0,10,(5,3))
print(data)

[[2 4 6]
 [8 2 8]
 [9 3 0]
 [0 1 0]
 [0 4 5]]


In [5]:
df = pd.DataFrame(data = data, columns = ['A','B','C'])
df.head()

A  B  C
0  2  4  6
1  8  2  8
2  9  3  0
3  0  1  0
4  0  4  5

In [6]:
df = pd.DataFrame(data = {
    'A': [1,2,3],
    'B': ['Hello','World','Mu']
})
df.head()

A      B
0  1  Hello
1  2  World
2  3     Mu

In [7]:
dtype = [('A',np.int), ('B',(np.str,20))]
data = np.array([(1,'tayyab'), (2,'Alex'), (3,'Jhon')], dtype = dtype)
df = pd.DataFrame(data)
df.head()


C:\Users\muhammad.tayyab01\AppData\Local\Temp\ipykernel_12720\3498868231.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = [('A',np.int), ('B',(np.str,20))]
C:\Users\muhammad.tayyab01\AppData\Local\Temp\ipykernel_12720\3498868231.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https:

A       B
0  1  tayyab
1  2    Alex
2  3    Jhon